---
- hosts: all
  become: yes
  tasks:
  - name: install git on ubuntu
    apt:
      name: git
      state: present
  - name: install tree on ubuntu
    apt:
      name: tree
      state: present
          